In [1]:
#Aufgabe 1
import numpy as np

array = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])

print("Array:")
print(array)
print("Shape:", array.shape)
print("Dimensions:", array.ndim)
print("Größe der Elemente in Bytes:", array.itemsize)


Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Shape: (5, 2)
Dimensions: 2
Größe der Elemente in Bytes: 4


In [53]:
import numpy as np


array = np.arange(100, 220, 20) 

# Verdoppeln des Arrays, um auf 10 Elemente zu kommen
array = np.concatenate([array, array[:4]])

array = array.reshape(5, 2)


print("Array:")
print(array)

Array:
[[100 120]
 [140 160]
 [180 200]
 [100 120]
 [140 160]]


In [57]:
#Aufgabe 3
import numpy as np

array = np.array([[10, 20, 30, 40],
                  [50, 60, 70, 80],
                  [90, 100, 110, 120],
                  [130, 140, 150, 160]])

third_column = array[:, 2]

print("Dritte Spalte:")
print(third_column)


Dritte Spalte:
[ 30  70 110 150]


In [59]:
#Aufgabe 4
import numpy as np

array1 = np.array([[8, 7, 6], [5, 4, 3]])
array2 = np.array([[2, 1, 0], [9, 8, 7]])

result = array1 - array2

squared_result = result ** 2

print("Ergebnis der Subtraktion:")
print(result)
print("Ergebnis nach Quadrieren:")
print(squared_result)


Ergebnis der Subtraktion:
[[ 6  6  6]
 [-4 -4 -4]]
Ergebnis nach Quadrieren:
[[36 36 36]
 [16 16 16]]


In [67]:
#Aufgabe 5
import numpy as np

array = np.array([[50, 51],
                  [52, 53],
                  [54, 55],
                  [56, 57],
                  [58, 59],
                  [60, 61],
                  [62, 63],
                  [64, 65]])
print("altes array:")
print(array)
print()
split_arrays = np.split(array, 4)


print("Aufgeteilte Arrays:")
for i, split_array in enumerate(split_arrays):
    print(f"Teil {i + 1}:")
    print(split_array)

altes array:
[[50 51]
 [52 53]
 [54 55]
 [56 57]
 [58 59]
 [60 61]
 [62 63]
 [64 65]]

Aufgeteilte Arrays:
Teil 1:
[[50 51]
 [52 53]]
Teil 2:
[[54 55]
 [56 57]]
Teil 3:
[[58 59]
 [60 61]]
Teil 4:
[[62 63]
 [64 65]]


In [73]:
# Aufgabe 6
import numpy as np

matrix = np.array([[10, 40, 30], [70, 20, 60], [50, 90, 80], [15, 25, 35]])

# Sortieren nach den Werten in der letzten Zeile (Index 2)
sorted_by_last_row = matrix[matrix[:, 2].argsort()]

# Sortieren nach den Werten in der zweiten Spalte (Index 1)
sorted_by_second_column = sorted_by_last_row[sorted_by_last_row[:, 1].argsort()]

# Ausgabe der sortierten Matrix
print("Matrix sortiert nach der letzten Zeile und dann der zweiten Spalte:")
print(sorted_by_second_column)


Matrix sortiert nach der letzten Zeile und dann der zweiten Spalte:
[[70 20 60]
 [15 25 35]
 [10 40 30]
 [50 90 80]]


In [81]:
#Aufgabe 7
import numpy as np

matrix = np.array([[12, 22, 32], [42, 52, 62], [72, 82, 92], [102, 112, 122]])

matrix[:, 2] = 0

print("Matrix nach dem Ersetzen der letzten Spalte mit Nullen:")
print(matrix)


Matrix nach dem Ersetzen der letzten Spalte mit Nullen:
[[ 12  22   0]
 [ 42  52   0]
 [ 72  82   0]
 [102 112   0]]


In [91]:
#Aufgabe 8
import numpy as np

matrix = np.array([[7, 5], [3, 2]])
print("die Matrix ist")
print(matrix)

Spur = np.trace(matrix)


determinante = np.linalg.det(matrix)

if determinante != 0:
    inverse = np.linalg.inv(matrix)
else:
    inverse = None

print("\nSpur der Matrix:", Spur)
print("Determinante der Matrix:", determinante)
if inverse is not None:
    print("Inverse der Matrix:")
    print(inverse)
else:
    print("Die Matrix ist nicht invertierbar (Determinante ist 0).")

die Matrix ist
[[7 5]
 [3 2]]

Spur der Matrix: 9
Determinante der Matrix: -0.9999999999999996
Inverse der Matrix:
[[-2.  5.]
 [ 3. -7.]]


In [95]:
#Aufgabe 9
import numpy as np

x1 = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0])
y1 = np.array([2.1, 3.9, 5.8, 7.7, 11.0, 12.0, 14.3, 16.2, 19.0, 19.9])
x2 = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0])
y2 = np.array([1.23, 1.48, 1.79, 2.16, 3.00, 3.32, 4.18, 5.05, 6.69, 7.32])


def calculate_statistics(data):
    mean = np.mean(data)
    median = np.median(data)
    q1, q3 = np.percentile(data, [25, 75])
    std_dev = np.std(data)
    return mean, median, q1, q3, std_dev

statistics_x1 = calculate_statistics(x1)
statistics_y1 = calculate_statistics(y1)
statistics_x2 = calculate_statistics(x2)
statistics_y2 = calculate_statistics(y2)

print("Statistik für x1:")
print(f"Mittelwert: {statistics_x1[0]}, Median: {statistics_x1[1]}, 1. Quartil: {statistics_x1[2]}, 3. Quartil: {statistics_x1[3]}, Standardabweichung: {statistics_x1[4]}")
print("\nStatistik für y1:")
print(f"Mittelwert: {statistics_y1[0]}, Median: {statistics_y1[1]}, 1. Quartil: {statistics_y1[2]}, 3. Quartil: {statistics_y1[3]}, Standardabweichung: {statistics_y1[4]}")
print("\nStatistik für x2:")
print(f"Mittelwert: {statistics_x2[0]}, Median: {statistics_x2[1]}, 1. Quartil: {statistics_x2[2]}, 3. Quartil: {statistics_x2[3]}, Standardabweichung: {statistics_x2[4]}")
print("\nStatistik für y2:")
print(f"Mittelwert: {statistics_y2[0]}, Median: {statistics_y2[1]}, 1. Quartil: {statistics_y2[2]}, 3. Quartil: {statistics_y2[3]}, Standardabweichung: {statistics_y2[4]}")

Statistik für x1:
Mittelwert: 5.5, Median: 5.5, 1. Quartil: 3.25, 3. Quartil: 7.75, Standardabweichung: 2.8722813232690143

Statistik für y1:
Mittelwert: 11.190000000000001, Median: 11.5, 1. Quartil: 6.275, 3. Quartil: 15.725, Standardabweichung: 5.910406077419724

Statistik für x2:
Mittelwert: 0.55, Median: 0.55, 1. Quartil: 0.325, 3. Quartil: 0.775, Standardabweichung: 0.2872281323269014

Statistik für y2:
Mittelwert: 3.622, Median: 3.16, 1. Quartil: 1.8825, 3. Quartil: 4.8325, Standardabweichung: 2.042546449900222


In [97]:
#Aufgabe 10
import numpy as np

x = np.array([4, 8, 6, 5, 3, 7, 9, 5])

mittelwert = np.mean(x)

empirische_varianz = np.sum((x - mittelwert)**2) / (len(x) - 1)

print(f"Mittelwert: {mittelwert}")
print(f"Empirische Varianz: {empirische_varianz}")




Mittelwert: 5.875
Empirische Varianz: 4.125
